import turtle

turtle.showturtle()
turtle.color('red')
turtle.pensize(10)
turtle.speed(2)
turtle.penup()
turtle.goto(-100, 0)
turtle.pendown()
turtle.forward(200)
turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
turtle.right(90)
turtle.forward(200)
turtle.done()